### PR TITLE
Update Rules block php supply chain attack

### PR DESCRIPTION
**Pull request by vncloudsco**
More info: https://news-web.php.net/php.internals/113838

### CODE REVIEW

**Comment by wargio** [comment]
please resolve the conflicts.

**Comment by vncloudsco** [comment]
@wargio conflicts has fixed!

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
@axellink for visibility

**Comment by jvoisin** [comment]
This never made it into production in any way. What is the point of blocking it?

**Comment by wargio** [comment]
depends by who uses git.php.net

**Review by axellink — APPROVED** [review]

**Pull request merged**
